name: statusesapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Service locator
  get_it: ^5.0.4
  # Riverpod for state management
  flutter_riverpod: ^0.12.2
  # Value equality
  equatable: ^1.2.5
  # Functional programming thingies
  dartz: ^0.9.2
  # Remote API
  data_connection_checker: ^0.3.4
  dio: ^3.0.10
  # Local cache
  sqflite: ^1.3.2+4
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  device_preview: ^0.4.5
  # Finding commonly used locations on the filesystem
  path_provider: ^1.6.27
  # Bottom nav bar
  persistent_bottom_nav_bar: ^3.1.0
  # Special icons
  font_awesome_flutter: ^8.11.0
  # Allow sharing
  share: ^0.6.5+4
  # Show messages
  fluttertoast: ^7.1.6
  # Show dialog
  awesome_dialog: ^1.3.1
  # Check network connectivity
  connectivity: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.png"



flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Neo_Sans
      fonts:
        - asset: fonts/NeoSansArabicRegular.ttf